#!/bin/bash

BASE_URL="http://localhost:8080"

curl -X POST "$BASE_URL/admin/reset"

echo

USER_JSON="{\"password\":\"12345\",\"email\":\"phillip@spellweaver.com\"}"
USER_POST=$(curl -d "$USER_JSON" -X POST "$BASE_URL/api/users" --no-progress-meter)

USER_ID=$(echo "$USER_POST" | jq -r '.id')
EMAIL=$(echo "$USER_POST" | jq -r '.email')

echo "Created user: $EMAIL ($USER_ID)"

LOGIN_JSON="{\"password\":\"12345\",\"email\":\"phillip@spellweaver.com\"}"
LOGIN_POST=$(curl -d "$LOGIN_JSON" -X POST "$BASE_URL/api/login" --no-progress-meter)

TOKEN=$(echo "$LOGIN_POST" | jq -r '.token')

echo "Received token: $TOKEN"

CHIRP_JSON="{\"body\":\"01234 sharbert 56789\"}"
CHIRP_POST=$(curl -d "$CHIRP_JSON" -H "Authorization: Bearer $TOKEN" -X POST "$BASE_URL/api/chirps" --no-progress-meter)

echo "$CHIRP_POST"
